version: '3.8'
services:  
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: Blogdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: